### PR TITLE
Add on-error handler option

### PR DESCRIPTION
**Pull request by palfrey**
Same as the other handlers, just additional.

### CODE REVIEW

**Comment by kirang89** [comment]
@palfrey Nice! It'd be awesome if you could do the following:
- Add a test for the error handler 
- Update documentation to include this handler

**Comment by palfrey** [comment]
I've added documentation, but I can't seem to be able to cause it to trigger. I've been able to make it hit when I had an error in my actual application, but can't seem to figure out how to make httpkit break. It's in the spec (https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/onerror), but I'm not sure how to directly cause it. Attempts to connect to a wrong/bad socket cause spec failures, and I even tried changing the local test runner to chrome from phantomjs and no improvement!

**Comment by kirang89** [comment]
My sincere apologies for letting this thread slip through the cracks!

Since this is there in the websocket spec, this should just work. I'll go ahead and merge this PR.

**Comment by kirang89** [comment]
Thank you for taking your time and helping out! :)

**Comment by palfrey** [comment]
If you've got some time soon, a new release with these changes in would be much appreciated :)

**Comment by kirang89** [comment]
@palfrey Thanks for staying on top of this! I'll make a new release in the next day or two.

**Comment by palfrey** [comment]
Not a problem. I've just picked back up the project that was using this, and realised it was using a git checkout version rather than the released version still.

**Comment by kirang89** [comment]
@palfrey Had some free time now, so went ahead and cut a release. Thanks again for pointing it out 👍

**Pull request merged**
